export const Lang = {
    total: "Total",
    lastWeek: "Last week",
    thisWeek: "This week",
    eightWeek: "8 weeks",
    hours: "Hours",
    sum: "𝑓(x)=",
    price: "Price",
    client: "Client",
    project: "Project",
    day: "Day",
    summary: "Summary",
    export: "Export",
    close: "Close",
    showProjects: "Show projects",
    showClients: "Show clients",
    groupByProject: "Group by project",
};
